## Tensors

In [1]:
import torch

In [18]:
def describe(x):
    print("Type : ", x.type())
    print("Shape : ", x.shape)
    print("Value : \n{}".format(x) )

In [20]:
#Uniform random
describe(torch.rand(2, 3))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0.4633, 0.7738, 0.7403],
        [0.5819, 0.2134, 0.6991]])


In [21]:
#Tensor
describe(torch.Tensor(2, 3))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0.0000e+00, 0.0000e+00, 1.3494e-05],
        [1.3077e+22, 1.6913e+22, 1.6598e-07]])


In [22]:
#Random normal
describe(torch.randn(2, 3))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[ 0.5735,  0.6118,  1.3278],
        [-0.0742,  1.6232,  1.5018]])


**`Any PyTorch method with an underscore (_) refers to an inplace operation; 
that is, it modifies the content in place without creating a new object`**

In [23]:
describe(torch.zeros(2, 3))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [25]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [27]:
x.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [28]:
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


### Tensor using List

In [29]:
describe(torch.Tensor([[1, 2, 3], [4, 5, 6]]))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor from Numpy

In [30]:
import numpy as np

In [31]:
npy = np.random.rand(2, 3)
npy

array([[0.55837256, 0.43419582, 0.74068349],
       [0.42039081, 0.65737851, 0.49732008]])

In [33]:
#Gives error
describe(npy)

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [34]:
describe(torch.from_numpy(npy))

Type :  torch.DoubleTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0.5584, 0.4342, 0.7407],
        [0.4204, 0.6574, 0.4973]], dtype=torch.float64)


**`Notice that the type of the tensor is DoubleTensor instead of the default FloatTensor . 
This corresponds with the data type of the NumPy random matrix, a float64`**

### Tensor Types and Size

**`There are two ways to specify the initialization type: either by directly calling
the constructor of a specific tensor type, such as FloatTensor or LongTensor, 
or using a special method, torch.tensor() and providing the dtype`**

In [37]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [39]:
x = x.long()
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [41]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [42]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [43]:
x = x.float()
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor Operations

In [44]:
x = torch.rand(2, 3)
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0.8229, 0.8234, 0.1096],
        [0.8204, 0.4873, 0.3901]])


In [46]:
describe(torch.add(x, x))

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1.6458, 1.6468, 0.2191],
        [1.6408, 0.9746, 0.7801]])


In [47]:
describe(x + x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[1.6458, 1.6468, 0.2191],
        [1.6408, 0.9746, 0.7801]])


### Range

In [59]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [60]:
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([6])
Value : 
tensor([0, 1, 2, 3, 4, 5])


In [61]:
# Using torch.int64
x = torch.arange(6, dtype = torch.int64)
x

tensor([0, 1, 2, 3, 4, 5])

In [62]:
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([6])
Value : 
tensor([0, 1, 2, 3, 4, 5])


In [63]:
# Using torch.float64
x = torch.arange(6, dtype = torch.float64)
x

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [64]:
describe(x)

Type :  torch.DoubleTensor
Shape :  torch.Size([6])
Value : 
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [65]:
# Using float
x = torch.arange(6, dtype = float)
x

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [66]:
describe(x)

Type :  torch.DoubleTensor
Shape :  torch.Size([6])
Value : 
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [73]:
x = torch.arange(0, 6)
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([6])
Value : 
tensor([0, 1, 2, 3, 4, 5])


### View

In [74]:
x = x.view(2, 3)
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0, 1, 2],
        [3, 4, 5]])


### Operations along axis , rows = 0 , cloumns = 1

In [75]:
#Using axis
describe(torch.sum(x, axis = 0))

Type :  torch.LongTensor
Shape :  torch.Size([3])
Value : 
tensor([3, 5, 7])


In [77]:
# Using dim
describe(torch.sum(x, dim = 1))

Type :  torch.LongTensor
Shape :  torch.Size([2])
Value : 
tensor([ 3, 12])


### Transpose

In [78]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [79]:
describe(torch.transpose(x, 0, 1))

Type :  torch.LongTensor
Shape :  torch.Size([3, 2])
Value : 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Indexing, Slicicing and Joining

In [81]:
x = torch.arange(6).view(2, 3)
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [82]:
describe(x[:1, :2])

Type :  torch.LongTensor
Shape :  torch.Size([1, 2])
Value : 
tensor([[0, 1]])


In [83]:
describe(x[0, 1])

Type :  torch.LongTensor
Shape :  torch.Size([])
Value : 
1


### Complex Indexing and Slicing

In [99]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [100]:
# Selecting 0 and 2 column
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim = 1, index = indices))

Type :  torch.LongTensor
Shape :  torch.Size([2, 2])
Value : 
tensor([[0, 2],
        [3, 5]])


In [101]:
# Selection 0 row
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim = 0, index = indices))

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [102]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [103]:
# Another way
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type :  torch.LongTensor
Shape :  torch.Size([2])
Value : 
tensor([0, 4])


In [104]:
describe(row_indices)

Type :  torch.LongTensor
Shape :  torch.Size([2])
Value : 
tensor([0, 1])


In [97]:
describe(col_indices)

Type :  torch.LongTensor
Shape :  torch.Size([2])
Value : 
tensor([0, 1])


**`Notice that the indices are a LongTensor; 
this is a requirement for indexing using PyTorch functions.`**

### Concatenating Tensors

In [107]:
x = torch.arange(6).view(2, 3)
describe(x)

Type :  torch.LongTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [109]:
describe(torch.cat([x, x], dim = 0))

Type :  torch.LongTensor
Shape :  torch.Size([4, 3])
Value : 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [110]:
describe(torch.cat([x, x], dim = 1))

Type :  torch.LongTensor
Shape :  torch.Size([2, 6])
Value : 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


### Stack

In [113]:
describe(torch.stack([x, x], dim = 0))

Type :  torch.LongTensor
Shape :  torch.Size([2, 2, 3])
Value : 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [112]:
describe(torch.stack([x, x], dim = 1))

Type :  torch.LongTensor
Shape :  torch.Size([2, 2, 3])
Value : 
tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5]]])


### Linear Algebra on Tensors

In [127]:
x1 = torch.arange(6, dtype = torch.float64).view(2, 3)
describe(x1)

Type :  torch.DoubleTensor
Shape :  torch.Size([2, 3])
Value : 
tensor([[0., 1., 2.],
        [3., 4., 5.]], dtype=torch.float64)


In [129]:
x2 = torch.ones((3, 2), dtype = torch.float64)
describe(x2)

Type :  torch.DoubleTensor
Shape :  torch.Size([3, 2])
Value : 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [130]:
x2[:, 1] += 1
describe(x2)

Type :  torch.DoubleTensor
Shape :  torch.Size([3, 2])
Value : 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]], dtype=torch.float64)


In [131]:
# Matrix Multiplication
describe(torch.mm(x1, x2))

Type :  torch.DoubleTensor
Shape :  torch.Size([2, 2])
Value : 
tensor([[ 3.,  6.],
        [12., 24.]], dtype=torch.float64)


### Tensors and Computational Graphs

`PyTorch tensor class encapsulates the data (the tensor itself) and a range of operations, such as algebraic operations, indexing, and reshaping operations. However, as shown in when the requires_grad Boolean flag is set to True on a tensor, bookkeeping operations are enabled that can track the gradient at the tensor as well as the gradient function, both of which are needed to facilitate the gradientbased learning discussed in“The Supervised Learning Paradigm”.`

In [134]:
x = torch.ones(2, 2, requires_grad = True)
describe(x)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 2])
Value : 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [135]:
print(x.grad is None)

True


In [136]:
print(x.grad)

None


In [137]:
y = (x + 2)*(x + 5) + 3
describe(y)

Type :  torch.FloatTensor
Shape :  torch.Size([2, 2])
Value : 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


In [138]:
print(x.grad is None)

True


In [139]:
z = y.mean()
describe(z)

Type :  torch.FloatTensor
Shape :  torch.Size([])
Value : 
21.0


In [140]:
z.backward()

In [141]:
print(x.grad is None)

False


`When you create a tensor with requires_grad=True, you are requiring PyTorch to manage bookkeeping information that computes gradients. First, PyTorch will keep track of the values of the forward pass. Then, at the end of the computations, a single scalar is used to compute a backward pass. The backward pass is initiated by using the backward() method on a tensor resulting from the evaluation of a loss function. The backward pass computes a gradient value for a tensor object that participated in the forward pass.`

`In general, the gradient is a value that represents the slope of a function output with respect to the function input. In the computational graph setting, gradients exist for each parameter in the model and can be thought of as the parameter’s contribution to the error signal. In PyTorch, you can access the gradients for the nodes in the computational graph by using the .grad member variable. Optimizers use the .grad variable to update the values of the parameters.`

### CUDA Tensors

In [142]:
torch.cuda.is_available()

True

In [144]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [145]:
x = torch.rand(3, 3).to(device)
describe(x)

Type :  torch.cuda.FloatTensor
Shape :  torch.Size([3, 3])
Value : 
tensor([[0.6444, 0.9906, 0.5484],
        [0.2136, 0.4027, 0.2563],
        [0.4840, 0.1204, 0.0312]], device='cuda:0')


In [146]:
y = torch.rand(3, 3)
y

tensor([[0.2991, 0.3763, 0.9301],
        [0.6781, 0.3505, 0.3314],
        [0.5423, 0.9811, 0.3947]])

In [147]:
#Error Code

z = x + y
z

RuntimeError: expected device cuda:0 but got device cpu

In [149]:
cpu_device = torch.device('cpu')
x = x.to(cpu_device)
y = y.to(cpu_device)

x + y

tensor([[0.9435, 1.3669, 1.4784],
        [0.8918, 0.7532, 0.5877],
        [1.0263, 1.1015, 0.4259]])

In [ ]:
`Keep in mind that it is expensive to move data back and forth from the GPU. Therefore, the typical
procedure involves doing many of the parallelizable computations on the GPU and then transferring
just the final result back to the CPU`