# Introduction to Pytorch

In [1]:
import torch

In [2]:
# Empty Tensor
x = torch.empty(1)
print(x)

tensor([0.])


In [3]:
x = torch.empty(2, 1)
print(x)

tensor([[0.],
        [0.]])


In [4]:
#Random
x = torch.rand(2, 2)
x

tensor([[0.7678, 0.1611],
        [0.4412, 0.1998]])

In [5]:
#Zeros
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [7]:
#Ones
x = torch.ones(3, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Data Types
x.dtype

torch.float32

In [9]:
# Changing Data Type
x = torch.ones((3, 3), dtype = torch.int)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [10]:
x.dtype

torch.int32

In [11]:
#Size
x.size()

torch.Size([3, 3])

### Tensor

In [13]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

### Tensor Operations

In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x);print(y)

tensor([[0.0997, 0.1246],
        [0.4348, 0.7982]])
tensor([[0.1285, 0.4697],
        [0.3065, 0.3444]])


In [21]:
#Adding
z = x + y
print(z)

tensor([[0.2281, 0.5944],
        [0.7412, 1.1426]])


In [22]:
z = torch.add(x, y)
z

tensor([[0.2281, 0.5944],
        [0.7412, 1.1426]])

In [23]:
# In Pytorch Every function with _ underscore will do an inplace operation
z = y.add_(x)
z

tensor([[0.2281, 0.5944],
        [0.7412, 1.1426]])

In [24]:
#Substraction
z = x - y
z

tensor([[-0.1285, -0.4697],
        [-0.3065, -0.3444]])

In [26]:
z = torch.sub(x, y)
z


tensor([[-0.1285, -0.4697],
        [-0.3065, -0.3444]])

In [27]:
#Multiplication
z = torch.mul(x, y)
z

tensor([[0.0227, 0.0741],
        [0.3223, 0.9120]])

In [28]:
x

tensor([[0.0997, 0.1246],
        [0.4348, 0.7982]])

In [29]:
y

tensor([[0.2281, 0.5944],
        [0.7412, 1.1426]])

In [30]:
#Changing y inplace
y.mul_(x)

tensor([[0.0227, 0.0741],
        [0.3223, 0.9120]])

In [31]:
y

tensor([[0.0227, 0.0741],
        [0.3223, 0.9120]])

In [32]:
#Division
z = x/y
z

tensor([[4.3832, 1.6824],
        [1.3491, 0.8752]])

In [33]:
z = torch.div(x, y)
z

tensor([[4.3832, 1.6824],
        [1.3491, 0.8752]])

### Slicing Operation

In [34]:
x = torch.rand(5, 3)
x

tensor([[0.7724, 0.1206, 0.6333],
        [0.4107, 0.0700, 0.9118],
        [0.7163, 0.7563, 0.2032],
        [0.3362, 0.1934, 0.7799],
        [0.1983, 0.0265, 0.5643]])

In [35]:
#All rows and third column
x[:, 2]

tensor([0.6333, 0.9118, 0.2032, 0.7799, 0.5643])

In [36]:
# Second row second element
x[1, 1]

tensor(0.0700)

In [38]:
#Item method gives actual Value
x[1, 1].item()

0.06996697187423706

### Reshaping

In [40]:
x = torch.rand(4, 4)
x

tensor([[0.8979, 0.3748, 0.5936, 0.9076],
        [0.4132, 0.8118, 0.7370, 0.0570],
        [0.6938, 0.0410, 0.7620, 0.6507],
        [0.9429, 0.3508, 0.0742, 0.0464]])

In [41]:
x.reshape(2, 8)

tensor([[0.8979, 0.3748, 0.5936, 0.9076, 0.4132, 0.8118, 0.7370, 0.0570],
        [0.6938, 0.0410, 0.7620, 0.6507, 0.9429, 0.3508, 0.0742, 0.0464]])

In [42]:
x.view(16)

tensor([0.8979, 0.3748, 0.5936, 0.9076, 0.4132, 0.8118, 0.7370, 0.0570, 0.6938,
        0.0410, 0.7620, 0.6507, 0.9429, 0.3508, 0.0742, 0.0464])

In [48]:
y = x.view(-1, 8)
y

tensor([[0.8979, 0.3748, 0.5936, 0.9076, 0.4132, 0.8118, 0.7370, 0.0570],
        [0.6938, 0.0410, 0.7620, 0.6507, 0.9429, 0.3508, 0.0742, 0.0464]])

In [49]:
y.size()

torch.Size([2, 8])

### Converting Torch to Numpy

In [50]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [51]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [52]:
print(type(b))

<class 'numpy.ndarray'>


In [53]:
print(type(a))

<class 'torch.Tensor'>


In [54]:
#Tensor a is in GPU
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [57]:
# Tensor b is in CPU so it gives error
b.add_(1)
b

AttributeError: 'numpy.ndarray' object has no attribute 'add_'

### Converting Numpy to Torch

In [58]:
import numpy as np

In [60]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [61]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [62]:
a  += 1
a

array([2., 2., 2., 2., 2.])

In [63]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [64]:
# Change in 'a' brings change in 'b'

### To check CUDA

In [70]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    # To create tensor on GPU
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    
    y = y.to(device)
    
    z = x + y # This is on GPU it is much faster
#     print(z)
#     z.numpy() # Gives error because numpy detects CPU
    
    z = z.to("cpu")
    print(z)
    
    

tensor([2., 2., 2., 2., 2.])
