# Gradient Calculation with Autograd

In [1]:
import torch

In [2]:
x = torch.rand(3, requires_grad = True)
print(x)

tensor([0.2514, 0.5503, 0.7001], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([2.2514, 2.5503, 2.7001], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
print(z)

tensor([10.1378, 13.0079, 14.5810], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

tensor(12.5756, grad_fn=<MeanBackward0>)


In [6]:
z.backward()          #dy/dx
print(z)

tensor(12.5756, grad_fn=<MeanBackward0>)


In [8]:
print(x.grad)

tensor([3.0019, 3.4004, 3.6001])


# 2. Removing Scalar Value

In [9]:
x = torch.rand(3, requires_grad = True)
y = x + 2
z = y*y*2
print(z)

tensor([17.7998, 11.6066, 15.2728], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, .001])
z.backward(v)

In [11]:
print(x.grad)

tensor([1.1933, 9.6360, 0.0111])


# 3. Preventing Tracking History

In [ ]:
# 1. x.requires_grad_(False)
# 2. x.detach()
# 3. with torch.no_grad()

In [12]:
x = torch.rand(3, requires_grad = True)
x.requires_grad_(False)
print(x)

tensor([0.0276, 0.5854, 0.7655])


In [13]:
x = torch.rand(3, requires_grad = True)
y = x.detach()
print(y)

tensor([0.2114, 0.5212, 0.7775])


In [14]:
x = torch.rand(3, requires_grad = True)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.8478, 2.3067, 2.4061])


## Note for backward function

In [15]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(1):
    model_op = (weights * 3).sum()
    model_op.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


In [18]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(2):
    model_op = (weights * 3).sum()
    model_op.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [19]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_op = (weights * 3).sum()
    model_op.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


### So before we do next iteration we should use grad.zero_()

In [22]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_op = (weights * 3).sum()
    model_op.backward()
    print(weights.grad)
    weights.grad.zero_()
    

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
